# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
timesTwo <- function(x) {
    .Call(`_mstools_timesTwo`, x)
}

#' @export
encodePic <- function(data, result) {
    invisible(.Call(`_mstools_encodePic`, data, result))
}

#' @export
decodeLinear <- function(data, result) {
    invisible(.Call(`_mstools_decodeLinear`, data, result))
}

